# Generated by Django 2.1.7 on 2019-05-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_count', models.IntegerField(default=1)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_no', models.BigIntegerField(default=91)),
                ('status', models.CharField(default='Not Paid', max_length=12, verbose_name='STATUS')),
                ('referral', models.CharField(blank=True, max_length=30, null=True, verbose_name='REFERRAL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
