# Generated by Django 2.2 on 2019-04-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments1',
        ),
    ]
